import { Obra } from './types';

export const mockObras: Obra[] = [
  // ... suas obras 1, 2 e 3

  {
    id: '4',
    nome: 'Residencial Jardim das Flores',
    descricao: 'Condomínio de casas geminadas',
    dataInicio: '2024-04-20',
    tarefas: [
      {
        id: '4-1',
        local: 'Fundação',
        atividade: 'Escavação e concretagem',
        unidade: 'm³',
        quantidade: 150,
        valor: 22500,
        empreiteira: 'Concretar Engenharia',
        statusPagamento: 'pago',
      },
      {
        id: '4-2',
        local: 'Estrutura',
        atividade: 'Levantamento de pilares',
        unidade: 'unidade',
        quantidade: 20,
        valor: 18000,
        empreiteira: 'Estruturas Forte',
        statusPagamento: 'em_andamento',
      },
      {
        id: '4-3',
        local: 'Cobertura',
        atividade: 'Instalação de telhado cerâmico',
        unidade: 'm²',
        quantidade: 350,
        valor: 24500,
        empreiteira: 'Telhas Brasil',
        statusPagamento: 'pendente',
      },
      {
        id: '4-4',
        local: 'Instalações',
        atividade: 'Rede hidráulica',
        unidade: 'ponto',
        quantidade: 40,
        valor: 8000,
        empreiteira: 'Hidro Center',
        statusPagamento: 'em_andamento',
      },
      {
        id: '4-5',
        local: 'Instalações',
        atividade: 'Rede elétrica',
        unidade: 'ponto',
        quantidade: 60,
        valor: 12000,
        empreiteira: 'Eletro Master',
        statusPagamento: 'pendente',
      },
      {
        id: '4-6',
        local: 'Acabamento interno',
        atividade: 'Pintura geral',
        unidade: 'm²',
        quantidade: 400,
        valor: 16000,
        empreiteira: 'Tintas & Cia',
        statusPagamento: 'atrasado',
      },
      {
        id: '4-7',
        local: 'Acabamento interno',
        atividade: 'Assentamento de piso porcelanato',
        unidade: 'm²',
        quantidade: 250,
        valor: 22500,
        empreiteira: 'Pisos Premium',
        statusPagamento: 'pago',
      },
      {
        id: '4-8',
        local: 'Área comum',
        atividade: 'Paisagismo',
        unidade: 'm²',
        quantidade: 180,
        valor: 10800,
        empreiteira: 'Verde Vida',
        statusPagamento: 'em_andamento',
      },
      {
        id: '4-9',
        local: 'Garagem',
        atividade: 'Pavimentação',
        unidade: 'm²',
        quantidade: 200,
        valor: 16000,
        empreiteira: 'Asfaltos União',
        statusPagamento: 'pendente',
      },
      {
        id: '4-10',
        local: 'Portaria',
        atividade: 'Instalação de portão eletrônico',
        unidade: 'unidade',
        quantidade: 1,
        valor: 7500,
        empreiteira: 'SegPort Tech',
        statusPagamento: 'pago',
      },
    ],
  },
  {
    id: '5',
    nome: 'Hospital Municipal Vida Nova',
    descricao: 'Construção de hospital de médio porte',
    dataInicio: '2024-05-10',
    tarefas: [
      {
        id: '5-1',
        local: 'Fundação',
        atividade: 'Estacas pré-moldadas',
        unidade: 'm',
        quantidade: 500,
        valor: 75000,
        empreiteira: 'Fundatec',
        statusPagamento: 'pago',
      },
      {
        id: '5-2',
        local: 'Estrutura',
        atividade: 'Concretagem de lajes',
        unidade: 'm²',
        quantidade: 1000,
        valor: 95000,
        empreiteira: 'Concretar Engenharia',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-3',
        local: 'Estrutura',
        atividade: 'Colocação de vigas metálicas',
        unidade: 'ton',
        quantidade: 20,
        valor: 180000,
        empreiteira: 'Metal Forte',
        statusPagamento: 'pendente',
      },
      {
        id: '5-4',
        local: 'Cobertura',
        atividade: 'Telhado metálico',
        unidade: 'm²',
        quantidade: 800,
        valor: 64000,
        empreiteira: 'CobreBem',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-5',
        local: 'Instalações',
        atividade: 'Rede de gases hospitalares',
        unidade: 'ponto',
        quantidade: 50,
        valor: 50000,
        empreiteira: 'HospGases Ltda',
        statusPagamento: 'pendente',
      },
      {
        id: '5-6',
        local: 'Instalações',
        atividade: 'Rede elétrica hospitalar',
        unidade: 'ponto',
        quantidade: 200,
        valor: 40000,
        empreiteira: 'Eletro Master',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-7',
        local: 'Acabamento interno',
        atividade: 'Piso vinílico antiestático',
        unidade: 'm²',
        quantidade: 1500,
        valor: 135000,
        empreiteira: 'Pisos Premium',
        statusPagamento: 'pendente',
      },
      {
        id: '5-8',
        local: 'Acabamento interno',
        atividade: 'Forro acústico',
        unidade: 'm²',
        quantidade: 1200,
        valor: 96000,
        empreiteira: 'Acústica Total',
        statusPagamento: 'pago',
      },
      {
        id: '5-9',
        local: 'Acabamento interno',
        atividade: 'Pintura epóxi',
        unidade: 'm²',
        quantidade: 900,
        valor: 54000,
        empreiteira: 'Tintas & Cia',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-10',
        local: 'Ambulatório',
        atividade: 'Divisórias hospitalares',
        unidade: 'm²',
        quantidade: 400,
        valor: 32000,
        empreiteira: 'HospConstrutora',
        statusPagamento: 'pendente',
      },
      {
        id: '5-11',
        local: 'Enfermarias',
        atividade: 'Instalação de camas hospitalares',
        unidade: 'unidade',
        quantidade: 120,
        valor: 240000,
        empreiteira: 'MediTech',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-12',
        local: 'UTI',
        atividade: 'Instalação de monitores cardíacos',
        unidade: 'unidade',
        quantidade: 40,
        valor: 400000,
        empreiteira: 'CardioLife',
        statusPagamento: 'pendente',
      },
      {
        id: '5-13',
        local: 'Centro Cirúrgico',
        atividade: 'Montagem de salas cirúrgicas',
        unidade: 'unidade',
        quantidade: 5,
        valor: 500000,
        empreiteira: 'CirurgiTech',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-14',
        local: 'Laboratório',
        atividade: 'Instalação de bancadas inox',
        unidade: 'm²',
        quantidade: 200,
        valor: 60000,
        empreiteira: 'Inox Prime',
        statusPagamento: 'pago',
      },
      {
        id: '5-15',
        local: 'Recepção',
        atividade: 'Montagem de balcão de atendimento',
        unidade: 'unidade',
        quantidade: 1,
        valor: 15000,
        empreiteira: 'Moveis Hospitalares',
        statusPagamento: 'pendente',
      },
      {
        id: '5-16',
        local: 'Refeitório',
        atividade: 'Instalação de cozinha industrial',
        unidade: 'unidade',
        quantidade: 1,
        valor: 180000,
        empreiteira: 'CozinTec',
        statusPagamento: 'em_andamento',
      },
      {
        id: '5-17',
        local: 'Estacionamento',
        atividade: 'Pavimentação asfáltica',
        unidade: 'm²',
        quantidade: 3000,
        valor: 240000,
        empreiteira: 'Asfaltos União',
        statusPagamento: 'pendente',
      },
      {
        id: '5-18',
        local: 'Áreas externas',
        atividade: 'Paisagismo completo',
        unidade: 'm²',
        quantidade: 1000,
        valor: 60000,
        empreiteira: 'Verde Vida',
        statusPagamento: 'pago',
      },
      {
        id: '5-19',
        local: 'Segurança',
        atividade: 'Instalação de câmeras CFTV',
        unidade: 'unidade',
        quantidade: 60,
        valor: 90000,
        empreiteira: 'SegPort Tech',
        statusPagamento: 'pendente',
      },
      {
        id: '5-20',
        local: 'Portaria',
        atividade: 'Controle de acesso biométrico',
        unidade: 'unidade',
        quantidade: 4,
        valor: 40000,
        empreiteira: 'BioAccess Ltda',
        statusPagamento: 'em_andamento',
      },
    ],
  },
];
